##
## EPITECH PROJECT, 2020
## Project [WSL: Ubuntu-20.04]
## File description:
## Makefile
##


SRC	=	src/main.cpp	\

BINARY	=	groundhog

all:
	g++ -o $(BINARY) $(SRC)

clean:
	rm -rf *.o *.a

fclean: clean
	rm -rf $(NAME)

re:	fclean